# Generated by prepare-organizer-v0459-r01-r2.py
# Locks r01 vehicle-display metadata to the published v0.4.59 mapping.

from __future__ import annotations

import hashlib
import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
METADATA_PATH = REPO_ROOT / "src" / "organizer" / "fh6-vehicle-metadata.json"
ORGANIZER_PATH = REPO_ROOT / "src" / "organizer" / "livery-organizer-for-fh6.py"

EXPECTED_RECORD_COUNT = 636
EXPECTED_MAPPING_SHA256 = "cdd6e4ca8115f6a12ec82974dbc6b65dec2675f3f3029d4fc9a34bc116b876e9"
EXPECTED_SOURCE_URL = 'https://forza.net/fh6cars'
EXPECTED_SOURCE_UPDATED = '2026-08-13'


def _payload() -> dict:
    return json.loads(METADATA_PATH.read_text(encoding="utf-8"))


def _fingerprint(payload: dict) -> str:
    rows = [
        [
            int(car_id),
            item["year"],
            item["make"],
            item["model"],
            item["display_name"],
        ]
        for car_id, item in payload["records"].items()
    ]
    rows.sort(key=lambda row: row[0])
    canonical = json.dumps(
        rows, ensure_ascii=False, separators=(",", ":")
    ).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def test_vehicle_metadata_baseline_equivalence():
    payload = _payload()
    assert payload["schema_version"] == 1
    assert payload["dataset"] == "fh6-official-vehicle-metadata"
    assert payload["source"]["name"] == "Forza official car list"
    assert payload["source"]["url"] == EXPECTED_SOURCE_URL
    assert payload["source"]["updated"] == EXPECTED_SOURCE_UPDATED
    assert len(payload["records"]) == EXPECTED_RECORD_COUNT
    assert _fingerprint(payload) == EXPECTED_MAPPING_SHA256


def test_embedded_vehicle_metadata_was_removed():
    source = ORGANIZER_PATH.read_text(encoding="utf-8")
    assert "OFFICIAL_VEHICLE_METADATA: dict[" not in source
    assert 'VEHICLE_METADATA_FILENAME = "fh6-vehicle-metadata.json"' in source
    assert "vehicle_metadata_runtime_path()" in source
    assert "select_runtime_vehicle_metadata_path(" in source
    assert 'VERSION = "0.4.59-r08"' in source
    assert "body.compact.fh6-my-design-view-mode .fh6-my-design-column" in source
    assert "clamp(180px,15vw,230px)" in source
